apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-grafana.selectorLabels" . | nindent 4 }}
