{{- if include "mcp-server-lib.needsDeployment" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-server-lib.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-server-lib.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "mcp-server-lib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.config }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.secrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "mcp-server-lib.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mcp-server-lib.serviceAccountName" . }}
      containers:
        - name: {{ include "mcp-server-lib.containerName" . }}
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.config .Values.secrets }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ include "mcp-server-lib.fullname" . }}
            {{- end }}
            {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "mcp-server-lib.fullname" . }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | default 8080 }}
              protocol: TCP
{{- end }}