{{- if .Values.secrets }}
{{- $owner := lookup "apps/v1" "Deployment" .Release.Namespace (include "mcp-server-lib.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server-lib.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-server-lib.labels" . | nindent 4 }}
  {{- if $owner }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "mcp-server-lib.fullname" . }}
      uid: {{ $owner.metadata.uid }}
      controller: true
  {{- end }}
type: Opaque
{{- if .Values.secrets.stringData }}
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.secrets.data }}
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}