{{- if include "mcp-server-lib.needsDeployment" . }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-server-lib.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-server-lib.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end }}
{{- end }}