{{- if include "mcp-server-lib.needsDeployment" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-server-lib.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-server-lib.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-server-lib.selectorLabels" . | nindent 4 }}
{{- end }}