apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  GRAFANA_URL: {{ .Values.url }}
  GRAFANA_API_KEY: {{ .Values.apiKey }}
