apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kagent.fullname" . }}-engine
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.engine.replicas }}
  selector:
    matchLabels:
      {{- include "kagent.engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/engine-configmap.yaml") . | sha256sum }}
        {{- with .Values.engine.podAnnotations | default .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kagent.engine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.engine.imagePullSecrets | default .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (.Values.engine.podSecurityContext | default .Values.podSecurityContext) | nindent 8 }}
      serviceAccountName: {{ include "kagent.fullname" . }}-engine
      containers:
        - name: engine
          securityContext:
            {{- toYaml (.Values.engine.securityContext | default .Values.securityContext) | nindent 12 }}
          image: "{{ .Values.engine.image.registry }}/{{ .Values.engine.image.repository }}:{{ coalesce .Values.tag .Values.engine.image.tag .Chart.Version }}"
          imagePullPolicy: {{ .Values.engine.image.pullPolicy | default .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "kagent.fullname" . }}-engine
          ports:
            - name: http
              containerPort: {{ .Values.engine.service.ports.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.engine.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/version
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
