apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kagent.fullname" . }}-engine
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
