{{- if .Values.enabled -}}
{{- if .Values.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openai.apiKeySecretRef }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.openai.apiKeySecretKey }}: {{ .Values.openai.apiKey | b64enc }}
{{- end }}
{{- end }}
