apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "tools.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tools.labels" . | nindent 4 }}
spec:
  config:
    sse:
      sseReadTimeout: 5m0s
      timeout: 30s
      url: {{ include "tools.serverUrl" . }}
  description: "Kagent's Built In Tool Server"
