{{- $owner := lookup "apps/v1" "Deployment" .Release.Namespace (include "chart.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querydoc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "querydoc.labels" . | nindent 4 }}
  {{- if $owner }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "querydoc.fullname" . }}
      uid: {{ $owner.metadata.uid }}
      controller: true
  {{- end }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.config.openaiApiKey | b64enc }}
