{{- if .Values.enabled -}}
{{- if .Values.config.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openai.apiKeySecretRef }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "querydoc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.openai.apiKeySecretKey }}: {{ .Values.config.openaiApiKey | b64enc }}
{{- end }}
{{- end }}
