apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "querydoc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "querydoc.labels" . | nindent 4 }}
spec:
  config:
    streamableHttp:
      sseReadTimeout: 5m0s
      timeout: 30s
      url: {{ include "querydoc.serverUrl" . }}
  description: "Documentation Query Tool Server"
