apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-mcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "grafana-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.config }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "grafana-mcp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grafana-mcp.serviceAccountName" . }}
      containers:
        - name: grafana-mcp
          args:
            - "-t"
            - "stdio"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ include "grafana-mcp.fullname" . }}
            {{- end }}
            - secretRef:
                name: {{ include "grafana-mcp.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | default 8000 }}
              protocol: TCP
