{{- $owner := lookup "apps/v1" "Deployment" .Release.Namespace (include "chart.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-mcp.labels" . | nindent 4 }}
  {{- if $owner }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "grafana-mcp.fullname" . }}
      uid: {{ $owner.metadata.uid }}
      controller: true
  {{- end }}
type: Opaque
stringData:
  GRAFANA_URL: {{ .Values.url }}
  GRAFANA_API_KEY: {{ .Values.apiKey }}
