{{- if .Values.grafana.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.apiKeySecretRef }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.grafana.apiKeySecretKey }}: {{ .Values.grafana.apiKey | b64enc }}
{{- end }}
