{{- if .Values.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tools.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc }}
{{- end }}
